### ISSUE TITLE
Better SSL integration

### ISSUE THREAD

**Issue by PabloVallejo** [CachetHQ/Docker#158]
I've successfully added SSL to the status page, I had to modify Dockerfile so that it copied the ssl files to the container.

Does adding an empty folder (conf/ssl) that is then copied in Dockerfile and also exposing port 443  make sense to you, if yes I can add a PR with those changes so that other users can setup setup connections easily. 

Thanks,

**Comment by gamkiller77** [comment]
I would just submit the PR.  I have done this already for other parts.  Adding and expose for port 443 would make a ton of sense.

**Comment by jgimenez** [comment]
If you'd like to keep a modular design, maybe you would like to have an nginx in front of Cachet. I use @jwilder/nginx-proxy in a docker-compose like this, this image even has the option to use Let's Encrypt to automatically generate the certificates:

```
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
    environment:
      - DEFAULT_HOST=status.xxxx.com
    restart: always
```

Also there are other options like [Traefik](https://traefik.io/)
