### ISSUE TITLE
SMTP mail driver won't send emails

### ISSUE THREAD

**Issue by fernandoneto** [CachetHQ/Docker#30]
Im trying to configure cachethq to send emails to subscrivers, but emails never reach destiny.
this is how my `docker-compose.yml` configuration

```
mysql:
  restart: always
  ports:
  - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: cachethq
    MYSQL_PASSWORD: password
    MYSQL_DATABASE: cachethq
  image: mysql:latest
  stdin_open: true

cachethq:
  restart: always
  ports:
  -  "8000:8000"
  environment:
    DB_DRIVER: mysql
    DB_HOST: mysql-server
    DB_DATABASE: cachethq
    DB_USERNAME: root
    DB_PASSWORD: password
    MAIL_DRIVER: smtp
    MAIL_HOST: mail.example.com
    MAIL_PORT: '25'
    MAIL_USERNAME: cachethq@example.com
    MAIL_PASSWORD: somepassword
    MAIL_ADDRESS: cachethq@example.com
    MAIL_NAME: cachethq@example.com
  image: cachethq/docker:latest
  links:
  - mysql:mysql-server
  stdin_open: true
```

Im using my email server.
