### ISSUE TITLE
Using volume to persist db data

### ISSUE THREAD

**Issue by khelll** [CachetHQ/Docker#92]
The motivation here is to make it easier to make it safer to persist the db data in case of accidental deletion of the db container or in case of upgrades:

https://docs.docker.com/compose/compose-file/#volumes-volume-driver

The change will be in docker-compose.yml
```yml
# ...
  postgres:
    image: postgres:9.5
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
# ...
```
